
import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: "Allen Solly Men's Polo T-Shirt",
    price: 1450.00,
    originalPrice: 2900.00,
    rating: 4.8,
    reviewCount: 24,
    description: "Virgil Abloh's Off-White is a streetwear-inspired collection that continues to break away from the conventions of mainstream fashion. Made in Italy, these premium polo shirts offer unmatched comfort and style.",
    images: [
      "https://picsum.photos/id/10/800/1000",
      "https://picsum.photos/id/11/800/1000",
      "https://picsum.photos/id/12/800/1000",
      "https://picsum.photos/id/13/800/1000"
    ],
    colors: ['#2563eb', '#dc2626', '#15803d', '#facc15'],
    sizes: ['S', 'M', 'L', 'XL'],
    productId: '#BHU5879',
    deliveryRegions: ['Dhaka', 'Chittagong', 'Sylhet'],
    category: 'Apparel',
    isMain: true,
    isActive: true,
    stock: 124,
    discountPercentage: 50,
    purchaseCost: 600.00,
    internalPrice: 1000.00,
    hasSizes: true,
    hasColors: true
  },
  {
    id: '2',
    name: "Classic Leather Sneakers",
    price: 3200.00,
    originalPrice: 4500.00,
    rating: 4.5,
    reviewCount: 112,
    description: "Handcrafted Italian leather sneakers with minimalist aesthetic and ergonomic sole for all-day comfort.",
    images: ["https://picsum.photos/id/21/800/1000"],
    colors: ['#000000', '#ffffff'],
    sizes: ['8', '9', '10', '11'],
    productId: '#SNK2210',
    deliveryRegions: ['Worldwide'],
    category: 'Footwear',
    isActive: true,
    stock: 45,
    discountPercentage: 25,
    purchaseCost: 1800.00,
    internalPrice: 2500.00,
    hasSizes: true,
    hasColors: true
  },
  {
    id: '3',
    name: "Minimalist Chronograph Watch",
    price: 5500.00,
    originalPrice: 7500.00,
    rating: 4.9,
    reviewCount: 45,
    description: "Sleek stainless steel watch featuring a sapphire crystal face and premium leather strap.",
    images: ["https://picsum.photos/id/31/800/1000"],
    colors: ['#111827', '#4b5563'],
    sizes: ['OS'],
    productId: '#WTC993',
    deliveryRegions: ['Worldwide'],
    category: 'Accessories',
    isActive: true,
    stock: 12,
    discountPercentage: 20,
    purchaseCost: 3500.00,
    internalPrice: 4500.00,
    hasSizes: false,
    hasColors: true
  },
  {
    id: '4',
    name: "Urban Explorer Backpack",
    price: 2400.00,
    originalPrice: 3200.00,
    rating: 4.7,
    reviewCount: 88,
    description: "Weather-resistant nylon backpack with padded laptop compartment and multiple utility pockets.",
    images: ["https://picsum.photos/id/48/800/1000"],
    colors: ['#1e293b', '#064e3b'],
    sizes: ['OS'],
    productId: '#BPK445',
    deliveryRegions: ['Dhaka', 'Rajshahi'],
    category: 'Bags',
    isActive: true,
    stock: 32,
    discountPercentage: 21,
    purchaseCost: 1200.00,
    internalPrice: 1800.00,
    hasSizes: false,
    hasColors: false
  }
];
