
import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: "Nature Shampoo Bar",
    price: 450.00,
    originalPrice: 650.00,
    rating: 4.9,
    reviewCount: 24,
    description: "প্রাকৃতিক যত্নে চুল হোক আরও শক্ত, ঘন ও প্রাণবন্ত। চুল পড়া, খুশকি ও রুক্ষতা দূর করতে ব্যবহার করুন আমাদের ভেষজ শ্যাম্পু বার। এতে আছে Cacumen Biotae ও Usman Grass এর মতো দুর্লভ প্রাকৃতিক উপাদান যা চুলের গোড়া মজবুত করে এবং নতুন চুল গজাতে সাহায্য করে।",
    shortDescription: "Organic Hair Care Solution",
    images: [
      "https://images.unsplash.com/photo-1608248597279-f99d160bfbc8?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1623631484728-66229503eb89?q=80&w=1000&auto=format&fit=crop"
    ],
    colors: ['#3F4E4F', '#A27B5C'],
    sizes: ['100g'],
    productId: '#NSB001',
    deliveryRegions: ['Nationwide'],
    category: 'Hair Care',
    isMain: true,
    isActive: true,
    stock: 200,
    discountPercentage: 30,
    purchaseCost: 150.00,
    internalPrice: 300.00,
    hasSizes: false,
    hasColors: false
  },
  {
    id: '2',
    name: "Classic Leather Sneakers",
    price: 3200.00,
    originalPrice: 4500.00,
    rating: 4.5,
    reviewCount: 112,
    description: "Handcrafted Italian leather sneakers with minimalist aesthetic and ergonomic sole for all-day comfort.",
    images: ["https://picsum.photos/id/21/800/1000"],
    colors: ['#000000', '#ffffff'],
    sizes: ['8', '9', '10', '11'],
    productId: '#SNK2210',
    deliveryRegions: ['Worldwide'],
    category: 'Footwear',
    isActive: true,
    stock: 45,
    discountPercentage: 25,
    purchaseCost: 1800.00,
    internalPrice: 2500.00,
    hasSizes: true,
    hasColors: true
  },
  {
    id: '3',
    name: "Minimalist Chronograph Watch",
    price: 5500.00,
    originalPrice: 7500.00,
    rating: 4.9,
    reviewCount: 45,
    description: "Sleek stainless steel watch featuring a sapphire crystal face and premium leather strap.",
    images: ["https://picsum.photos/id/31/800/1000"],
    colors: ['#111827', '#4b5563'],
    sizes: ['OS'],
    productId: '#WTC993',
    deliveryRegions: ['Worldwide'],
    category: 'Accessories',
    isActive: true,
    stock: 12,
    discountPercentage: 20,
    purchaseCost: 3500.00,
    internalPrice: 4500.00,
    hasSizes: false,
    hasColors: true
  },
  {
    id: '4',
    name: "Urban Explorer Backpack",
    price: 2400.00,
    originalPrice: 3200.00,
    rating: 4.7,
    reviewCount: 88,
    description: "Weather-resistant nylon backpack with padded laptop compartment and multiple utility pockets.",
    images: ["https://picsum.photos/id/48/800/1000"],
    colors: ['#1e293b', '#064e3b'],
    sizes: ['OS'],
    productId: '#BPK445',
    deliveryRegions: ['Dhaka', 'Rajshahi'],
    category: 'Bags',
    isActive: true,
    stock: 32,
    discountPercentage: 21,
    purchaseCost: 1200.00,
    internalPrice: 1800.00,
    hasSizes: false,
    hasColors: false
  }
];
